/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: '#5f9b8f',
          light: '#7ab3a8',
          lighter: '#e8f4f1',
          dark: '#4a7d73',
        },
        primary: {
          DEFAULT: '#5f9b8f',
          light: '#7ab3a8',
          dark: '#4a7d73',
        },
        secondary: '#2b3d4f',
        accent: '#5f9b8f',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        info: '#3b82f6',
        bg: {
          DEFAULT: '#f5f5f5',
          secondary: '#f8f9fa',
          gray: '#fafbfc',
        },
        layer: {
          0: '#f5f5f5',
          1: '#f8f9fa',
          2: '#ffffff',
          header: '#f8f9fa',
          modal: '#ffffff',
        },
        text: {
          primary: '#2b3d4f',
          secondary: '#6c757d',
          tertiary: '#9ca3af',
          muted: '#999999',
        },
        border: {
          DEFAULT: '#e5e7eb',
          light: '#f0f1f3',
        },
        chart: {
          1: '#5f9b8f',
          2: '#2b3d4f',
          3: '#7ab3a8',
          4: '#10b981',
          5: '#ef4444',
          up: '#10b981',
          down: '#ef4444',
        },
      },
      fontFamily: {
        sans: ['Pretendard Variable', 'Pretendard', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'Roboto', 'sans-serif'],
        numeric: ['Roboto', 'Pretendard Variable', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'xs': '12px',
        'sm': '14px',
        'base': '16px',
        'lg': '18px',
        'xl': '20px',
        '2xl': '24px',
        '3xl': '32px',
        '4xl': '48px',
        'hero': '72px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '48px',
        'header': '64px',
        'bottom-nav': '64px',
        'sidebar': '230px',
        'sidebar-collapsed': '72px',
        'content-max': '1400px',
        'touch': '44px',
      },
      borderRadius: {
        'sm': '4px',
        'md': '4px',
        'lg': '6px',
        'xl': '8px',
      },
      boxShadow: {
        'sm': '0 1px 2px rgba(0, 0, 0, 0.06)',
        'md': '0 2px 4px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.06)',
        'lg': '0 4px 8px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.06)',
        'xl': '0 8px 16px rgba(0, 0, 0, 0.10), 0 4px 8px rgba(0, 0, 0, 0.08)',
        'card': '0 1px 3px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.06)',
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '200ms',
        'slow': '300ms',
      },
      width: {
        'icon-xs': '16px',
        'icon-sm': '20px',
        'icon-md': '24px',
        'icon-lg': '32px',
        'icon-xl': '48px',
      },
      height: {
        'icon-xs': '16px',
        'icon-sm': '20px',
        'icon-md': '24px',
        'icon-lg': '32px',
        'icon-xl': '48px',
      },
      animation: {
        'fade-slide-up': 'fadeSlideUp 0.5s ease-out forwards',
        'slide-in-up': 'slideInUp 0.3s ease-out forwards',
        'spin-slow': 'spin 1s linear infinite',
        'pulse-required': 'pulseRequired 2s ease-in-out infinite',
      },
      keyframes: {
        fadeSlideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseRequired: {
          '0%, 100%': { boxShadow: '0 0 0 4px rgba(239, 68, 68, 0.1), 0 4px 12px rgba(239, 68, 68, 0.15)' },
          '50%': { boxShadow: '0 0 0 6px rgba(239, 68, 68, 0.15), 0 6px 16px rgba(239, 68, 68, 0.2)' },
        },
      },
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1400px',
      },
    },
  },
  plugins: [],
}
